### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by HarshitNagar** [GalAvineri/ISIC-Archive-Downloader#10]
File "download_archive.py", line 84
    def download_descriptions(ids: list, descs_dir: str, num_processes: int) -> list:
                                                  ^
SyntaxError: invalid syntax

**Comment by GalAvineri** [comment]
Hmm I can't seem to reproduce it
Can you do 2 things for me?
1. Make sure you have the latest version of this repository
2. Tell me what is the result of `python --version`

**Comment by HarshitNagar** [comment]
Thank you so much for your time. It is working now. I was running it on python 2. Sorry for creating an issue which was not there in the first place.

**Comment by GalAvineri** [comment]
On the contrary my friend!
At the time you submitted your issue, the project did not ask for python 3 as a necessity.
After you submitted your issue, I suspected that it should have been, which is why I asked you for your python version.

You can even see that I updated the README file to contain the python 3 requirement a couple of days after you submitted your issue.
So you were completely on to an issue! :)

I'm glad it's working well for you now, and thank you for bringing up this issue!

**Comment by HarshitNagar** [comment]
I thought i had missed the python 3 part in the readme. Glad it all worked out.
