### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by fabiomaia** [GalAvineri/ISIC-Archive-Downloader#19]
I am using this script for my MSc thesis (thanks!) as a subtree module

```
git subtree add --prefix ISIC-Archive-Downloader git@github.com:GalAvineri/ISIC-Archive-Downloader.git master --squash;
```

But, of course, I don't want to version control the downloaded data. It would be wise to `.gitignore` the `./Data` directory specifically. While you're at it, consider a good `.gitignore` from https://www.gitignore.io/api/vim,osx,emacs,linux,python,windows,webstorm,sublimetext,visualstudiocode

**Comment by GalAvineri** [comment]
Hey Fabio!
First of all, thank you for letting me know this repository is helping you with you MSc thesis, you made me happy :)

Secondly, I agree that adding a ```.gitignore``` that covers the outputs of the default behavior and enables easier extension and modification of the repository is a great idea :)
So thank you for that! i'll add it a soon as i can :)

Regarding your second suggestion, for using a premade, comprehansive ```.gitignore```:
The repository currently produces only a few outputs, therefore I think that it might be better to relate to them using a simple ```.gitignore``` instead of adding a big ```.gitignore``` that covers many things this repository does not produce.

One of the reasons I think that a small and accurate ```.gitignore``` would more useful is the following:
If later I would like to change the affect of the ```.gitignore``` on the outputs of the repository, it would be harder to understand what to change in the massive ```.gitignore```, but it would be much easier to inflict the change in a simple ```.gitignore```.

What are your thoughts about this? :)

**Comment by GalAvineri** [comment]
Added the .gitignore we agreed upon in d93a738 :)
Thank you for the great suggestion!

Feel free to reopen this if needed :)
