### ISSUE TITLE
Problem with new parallel version

### ISSUE THREAD

**Issue by javism** [GalAvineri/ISIC-Archive-Downloader#2]
I am running the new code in Python 2.7.12 in Linux and I get the following error. In addition no image/description was downloaded: 

$ python download_dataset.py 
Collecting all images ids
Thread 0 started
Thread 1 started
 downloading image (0/29)
downloading image (30/39)
url_image = https://isic-archive.com/api/v1/image/5436e3abbae478396759f0cf/download?contentDisposition=inline
...
downloading image (27/29)
url_image = https://isic-archive.com/api/v1/image/5436e3aebae478396759f105/download?contentDisposition=inline
downloading image (28/29)
url_image = https://isic-archive.com/api/v1/image/5436e3aebae478396759f107/download?contentDisposition=inline
Traceback (most recent call last):
  File "download_dataset.py", line 95, in <module>
    download_dataset()
  File "download_dataset.py", line 71, in download_dataset
    print('Thread {0} finished'.format(thread._Thread__kwargs['thread_id']))
AttributeError: 'Thread' object has no attribute '_Thread__kwargs'

**Comment by GalAvineri** [comment]
Thanks for bringing this up, i'm gonna check it soon :)

**Comment by GalAvineri** [comment]
_Thread_kwargs is a protected class variable, and for some reason my program could access it but yours could'nt.

In any case instead of printing the "thread X finished" in the main program i moved it to be printed from inside the thread itself, which is also better from the code prospective because now it doesn't access protected variables :P 

Could you give it a try and tell me if it works for you now? :)

**Comment by javism** [comment]
Now is working even in Linux. I close the issue. Thanks.
