### ISSUE TITLE
where images are stored

### ISSUE THREAD

**Issue by FedericoLavatori** [GalAvineri/ISIC-Archive-Downloader#7]
Premises: I am a newbie and this is my first issue I am opening in GitHub.

I am trying to use your downloader because I need ISIC archive to build up and test GANs analysis by using Keras and TensorFlow packages. I am using Colab so as to exploit the GPU provided by Google and I am also having all scripts and data on GoogleDrive shared folder Assignment_1. Here is my code:

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

!mkdir -p drive
!google-drive-ocamlfuse drive

!pip install -r drive/Assignment_1/requirements.txt

!python3 drive/Assignment_1/download_dataset.py 13000

Question: Where are all images stored? Once I execute the code I get a __psycache__ folder with some .pyc files in it but I really don't know what do they stand for. The point is I tried to go through download_dataset_subset.py and download_dataset.py but I am not understanding it. When I type:

!python3 drive/Assignment_1/download_dataset.py 13000

I just can see:

Collecting the images ids
Downloading images and descriptions
 43% (5635 of 13000) |########

as first message and then updating messages until I reach 100% so I am pretty sure the download is complete.

**Comment by GalAvineri** [comment]
Congratulations on your first issue on github! :)

# Regarding your problem
The code chooses a path by default to download the images to.
Currently it is the following:
<d>/Data/Images
where <d> is the directory from which you called the script.
so due to the fact you executed:
'python3 drive/Assignment_1/download_dataset.py 13000'
i suspect the images will be found in the path 'drive/Data/Images'

# Another (Quick) Solution
As noted in the instructions in the README.MD file,
there is an optional parameter to define the location to download the images into.

So say you would like to download the images into drive/Assignment_1/Images
than you could execute the following:
'python3 drive/Assignment_1/download_dataset.py 13000 --images-dir drive/Assignment_1/Images'
and all the images will be downloaded to drive/Assignment_1/Images

Update me when you've tried one of these :)

**Comment by GalAvineri** [comment]
I haven't got an update from you yet, so i'll assume you've succeeded in locating the downloaded images :)
If you haven't found them yet, feel free to reopen this issue!
